[features]
seeds = false
skip-lint = false

[programs.localnet]
whitelist = "bdEDPr9KGtkSABS8Sg3gWeJKyQEaTQVaBRvCu38YMNz"
basket_factory = "sXShikYX7G5n3S3qp78RWQBxh2YJARLvufiCoaxjAyq"
basket = "37VPGtd57kXJ1HvH1xvdZr1y3s4KXj9pP2o6GdYLgbb1"

[programs.devnet]
whitelist = "bdEDPr9KGtkSABS8Sg3gWeJKyQEaTQVaBRvCu38YMNz"
basket_factory = "sXShikYX7G5n3S3qp78RWQBxh2YJARLvufiCoaxjAyq"
basket = "37VPGtd57kXJ1HvH1xvdZr1y3s4KXj9pP2o6GdYLgbb1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"
